blank_issues_enabled: false
contact_links:
  - name: Telegram Group
    url: https://t.me/tclupdates_discussion
    about: Join our community for real-time support and technical discussions.
  - name: Telegram Channel
    url: https://t.me/tclupdates
    about: Stay updated with the latest firmware releases.
